version: "2.0"
services:
  frontend:
    build:
      args:
        - BACKEND_API=http://localhost:5113
      context: ./frontend
      dockerfile: Dockerfile
    image: halma-frontend
    ports:
      - 8081:80
